In [8]:
-#Reading text file
'''with ka key_word file ko read krne k bd automatically file ko close krdyta hai'''
with open('8th class text file.txt') as practicefile: #(data get)txt file ka data practicefile k name se excess hoga ab yhn.. we take the other name rathan than practicefile
    content = practicefile.read()
    print(content.rstrip())  #rstrip() txt file k text end hne k bd extra line ko(space line) ko print nhi krwata(ignore krta hai )

123
456
789


In [10]:
#Reading text file
with open('Ninth class folder/9th class text2.txt') as practicefile: 
    content = practicefile.read()
    print(content.rstrip()) 

Muhammad
Sarfraz
Aslam


In [11]:
filepath = 'Ninth class folder/9th class text2.txt'
with open(filepath) as practicefile: 
    content = practicefile.read()
    print(content.rstrip()) 

Muhammad
Sarfraz
Aslam


In [15]:
#Reading text file with loop
filepath2 ='8th class text file.txt'
with open(filepath2) as prac:
    contents = prac.read()
    
for line in contents:
    print(line)

1
2
3


4
5
6


7
8
9










In [16]:
#Reading text file with loop
filepath2 ='8th class text file.txt'
with open(filepath2) as prac:
    contents = prac.readlines()
    
for line in contents:
    print(line)

123

456

789









In [17]:
#Reading text file with loop
filepath2 ='8th class text file.txt'
with open(filepath2) as prac:
    contents = prac.readlines()
    
for line in contents:
    print(line.rstrip())

123
456
789





In [2]:
#Reading text file with loop
filepath2 ='8th class text file.txt'
with open(filepath2) as prac:
    contents = prac.readlines()
    
Oneline =""

for line in contents:
    Oneline +=line
print(Oneline)

123
456
789


In [24]:
#Reading text file with loop
filepath2 ='8th class text file.txt'
with open(filepath2) as prac:
    contents = prac.readlines()
    
Oneline = ""

for line in contents:
    Oneline +=line.rstrip()
print(Oneline)

123456789


In [38]:
#Reading text file with loop
filepath2 ='8th class text file.txt'
with open(filepath2) as prac:
    contents = prac.readlines()
    
Oneline = ""

for line in contents:
    Oneline +=line.rstrip()
print(Oneline[:6] + " " + "Still continue")
print(Oneline[0:6])
print(Oneline[1:6])
print(Oneline[3:9])
print(Oneline[6:9])
print("Length: " +str(len(Oneline)))

123456 Still continue
123456
23456
456789
789
Length: 9


In [55]:
#Writing text file 
#with ka method read file k lye bedefault hta hai ..write krne k liye "w" likhna zruri hai
#write k method se purana content remove hjyga text file se
filepath3 ='8th class text file 2.txt'

with open(filepath3,"w") as writefile:
    writefile.write("0000webhost.com \n")
    writefile.write("godaddy.com \n")

In [56]:
#Writing text file 
#How to save old content  during writing in text file ?

filepath4 ='8th class text file 2.txt'

with open(filepath4,"a") as writefiles:
    writefiles.write("fiver freelancing \n")
    writefiles.write("Upwork freelancing \n")

In [61]:
#Error control

firstnum=5
secondnum=0

try:
    answer =firstnum/secondnum
    
except ZeroDivisionError:
    print("This operation can not be performed")
    
else:
    print(answer)

This operation can not be performed


In [65]:
#FileNotFound Error
try:
    with open("0th.txt") as pract:
        contant = pract.read()
        
except FileNotFoundError:
    print("Your file path is not correct")
    
else:
    print(contant)

Your file path is not correct


In [20]:
#use\utilize csv file
import csv 

with open('FL_insurance_sample.csv') as csvfile:
    contant = csv.reader(csvfile)
    for line in contant:
        print(line)

['policyID', 'statecode', 'county', 'eq_site_limit', 'hu_site_limit']
['policyID', 'statecode', 'county', 'eq_site_limit', 'hu_site_limit']


In [37]:
#use\utilize csv file
import csv 

with open('EMail List first.csv') as csvfile:
    contant = csv.reader(csvfile)
    for line in contant:
        print(line)

[]
[]
['aamirpasha.pasha@gmail.com']
['abdulmananhere@gmail.com']
['adozdias@gmail.com']
['aeirc.pk@gmail.com']
['alikhokhar933@gmail.com']
['aljassarksa@gmail.com']
['amdadali537@gmail.com']
['ameel.khan@gmail.com']
['anieezakir12@gmail.com']
['arshan202@gmail.com']
['asfar.ali110@gmail.com']
['ataullah.khan@iiu.edu.pk']
['cvisb@gmail.com']
['docthers@gmail.com']
['dr.azzuri@gmail.com']
['dr.moheyuddin@gmail.com']
['drahmadyasin25@gmail.com']
['ehsanmunnir@gmail.com']
['ehtishamhrm7@gmail.com']
['faizurrehmanzahid@gmail.com']
['farooqrathore@gmail.com']
['g.umairyousaf@gmail.com']
['healthcare.jobs.pakistan@gmail.com']
['hometextilewarehouse@gmail.com']
['iaand.general@gmail.com']
['instinctshelp@gmail.com']
['jaak88@gmail.com']
['jabespk@gmail.com']
['jfernanmunoz@gmail.com']
['jpmc@gmail.com']
['kinzasaleem26@gmail.com']
['kwameatoapem@gmail.com']
['lasersu@gmail.com']
['levingtonkevin@gmail.com']
['luisfercz@gmail.com']
['mahathirmahmudantik@gmail.com']
['medicaldoctor87@gmail.com'

In [22]:
import math

print(math.pi)

3.141592653589793


In [28]:
import math as mysearch
print(mysearch.pi)

3.141592653589793


In [29]:
from math import pi
print(pi)

3.141592653589793


In [30]:
from math import *
print(pi)
print(e)

3.141592653589793
2.718281828459045


In [3]:
import math
print(math.ceil(5.2))
print(math.floor(4.8))

6
4


In [34]:
import import_ipynb 
import ninth_class_2 as new
new.add(5,3)

importing Jupyter notebook from ninth_class_2.ipynb


8

In [38]:
#Numpy 
#Its a module ..
# 2 = two array
# 3 = three random number
import numpy as np
data = np.random.randn(2,3)
print(data)

[[-0.8160316  -0.71669934 -0.13936203]
 [-1.09183178 -1.03405584  0.41025064]]


In [8]:
#Numpy 
#Its a module ..
# 2 = two array
# 3 = three random number
import numpy as np
data = np.random.randn(2,3)
print(data , "\n")
print(data + data,"\n")
print(data * 10,"\n")
print(data.shape,"\n")
print(data.dtype,"\n")
print(data.ndim,"\n")  #direction of array

[[-1.0144876   0.19240229 -0.54055355]
 [ 0.42388706 -1.47865042 -0.08757627]] 

[[-2.0289752   0.38480457 -1.0811071 ]
 [ 0.84777412 -2.95730083 -0.17515254]] 

[[-10.14487599   1.92402287  -5.40553549]
 [  4.2388706  -14.78650416  -0.8757627 ]] 

(2, 3) 

float64 

2 



In [53]:
print(np.zeros(10),"\n")
print(np.zeros((3,6)),"\n")
print(np.zeros((2,3,6)),"\n")

print("It is empty example\n",np.empty((3,6)))
#empty sometimes garbig values bhi lakr dyta hai but mostly zeros lakr dyta hai



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

It is empty example
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [13]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.astype(np.float64))


[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [77]:
arr = np.array([4,2,6,8],dtype = 'int64')
print(arr*2,"\n")
print(arr*arr,"\n")
print(arr//2,"\n")
print(arr/2,"\n")
print(2/arr,"\n")
print(2//arr,"\n")
print(arr**2,"\n")
print(np.sqrt(arr),"\n")
print(np.exp(arr),"\n")
print(np.mean(arr),"\n")
print(np.sum(arr),"\n")
print(np.cumsum(arr),"\n")
print(np.sort(arr),"\n")

arr2 = np.array([0,1,3,9])

print(arr > arr2)

[ 8  4 12 16] 

[16  4 36 64] 

[2 1 3 4] 

[2. 1. 3. 4.] 

[0.5        1.         0.33333333 0.25      ] 

[0 1 0 0] 

[16  4 36 64] 

[2.         1.41421356 2.44948974 2.82842712] 

[  54.59815003    7.3890561   403.42879349 2980.95798704] 

5.0 

20 

[ 4  6 12 20] 

[2 4 6 8] 

[ True  True  True False]


In [80]:
arr = np.arange(10)
print(arr)
arr2= arr[5:8]
print(arr2)

arr[:3] =0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [89]:
namesArr = np.array(["Sarfraz","Zeeshan","Sarwar","Sarfraz","Aslam"])
numArr = np.random.randn(5,3)   # jitne array namesArr mai define kiya hai utne hi array(dimension) bnaege yhan manipulate krne k liye ..

print(numArr,"\n")
print(namesArr,"\n")
print(namesArr == "Sarfraz","\n")
print(numArr[ namesArr == "Sarfraz"],"\n")
print(numArr[ ~(namesArr == "Sarfraz")],"\n") #~(tidle) = not
print(np.unique(namesArr))   # sort and neglate multiple(repeated) element


[[-1.36212716 -1.36865407  0.27745326]
 [ 0.85330744  0.24559886 -0.40434328]
 [-0.2042942   2.00531978  0.30578412]
 [ 0.92367974  0.83415364 -1.16316412]
 [-0.69514216  0.09869909  2.02082314]] 

['Sarfraz' 'Zeeshan' 'Sarwar' 'Sarfraz' 'Aslam'] 

[ True False False  True False] 

[[-1.36212716 -1.36865407  0.27745326]
 [ 0.92367974  0.83415364 -1.16316412]] 

[[ 0.85330744  0.24559886 -0.40434328]
 [-0.2042942   2.00531978  0.30578412]
 [-0.69514216  0.09869909  2.02082314]] 

['Aslam' 'Sarfraz' 'Sarwar' 'Zeeshan']


In [94]:
arr = np.random.randn(4)
print(arr,"\n")

arr2 = np.random.randn(4)
print(arr2,"\n")

print(np.maximum(arr,arr2),"\n")
print(np.minimum(arr,arr2),"\n")

[-1.13625846  0.32377331  0.1884565   1.585851  ] 

[-1.36695143  0.137263    1.5443131  -0.88516645] 

[-1.13625846  0.32377331  1.5443131   1.585851  ] 

[-1.36695143  0.137263    0.1884565  -0.88516645] 

